import { createContext, useContext, useState } from 'react'

const languages = {
  es: {
    code: 'es',
    flag: '🇪🇸',
    name: 'Español',
    switchToLight: 'Cambiar a modo claro',
    switchToDark: 'Cambiar a modo oscuro',
    placeholder: '¿Qué quieres saber sobre la imagen?',
    upload: 'Haz clic para subir una imagen',
    analyze: 'Analizar imagen',
    analyzing: 'Analizando...',
    response: 'Respuesta',
    detections: 'Detecciones',
    history: 'Historial',
    clear: 'Limpiar',
    noDetections: 'Sin objetos detectables por YOLO',
    historyEmpty: 'Las consultas aparecerán aquí',
    conversationMode: 'Modo conversación',
    conversationModeDesc: 'Recuerda preguntas anteriores',
    startAudio: 'Grabar voz', 
    stopAudio: 'Detener grabación',
    transcribing: 'Transcribiendo...',
    tapToStopRecording: 'Pulsa de nuevo para transcribir',
    playAudio: 'Iniciar audio',
    pauseAudio: 'Detener audio',
    send: 'Enviar',
    activateCameraTooltip: 'Debes activar la cámara',
    title: 'Asistente Mini',
    subtitle: 'Habla, muestra, pregunta — Mini hace el resto',
    error: 'Error al conectar con el backend',
    queryTooLong: 'Tu pregunta es demasiado larga (máximo 1000 caracteres).',
    expand: '▼ ver más',
    collapse: '▲ cerrar',
    imageMode: 'Imagen',
    webcamMode: 'Webcam',
    startWebcam: 'Activar webcam',
    stopWebcam: 'Detener webcam',
    analyzeError: 'Error al analizar el frame',
    webcamError: 'No se pudo acceder a la webcam',
    clearImage: 'Quitar imagen',
    miniGreeting: '¿En qué te puedo ayudar hoy?',
    miniPlaceholder: 'Ej: enciende la cámara y dime qué ves...\n(Pulsa Enter para enviar)',
    tapToSpeak: 'Toca para hablar',
    userGuideTitle: 'Guía de Uso',
    guideMiniTitle: '¿Qué es el modo Mini?',
    guideMiniIntro1: 'Mini es un agente inteligente multimodal. No solo responde a tus preguntas, sino que ',
    guideMiniIntroBold: 'puede realizar acciones por ti',
    guideMiniIntro2: ' dependiendo de lo que le pidas.',
    guideMiniVisualBold: 'Autonomía visual',
    guideMiniVisualText: ': Si le pides que vea algo a tu alrededor, Mini encenderá la cámara web automáticamente o te abrirá el selector de archivos.',
    guideMiniVoiceBold: 'Voz y Texto',
    guideMiniVoiceText: ': Puedes escribirle o pulsar el icono del micrófono para hablarle directamente. También puedes escuchar sus respuestas pulsando el icono de audio en cada mensaje.',
    guideMiniConvBold: 'Modo Conversación',
    guideMiniConvText: ': Actívalo para que Mini recuerde el contexto. Ideal para hacerle preguntas de seguimiento.',
    guideClassicTitle: 'Modos Clásicos (Imagen y Webcam)',
    guideClassicIntro: 'Úsalos si prefieres tener el control manual completo sobre lo que estás enviando para analizar.',
    guideClassicImageBold: 'Imagen',
    guideClassicImageText: ': Sube una foto de tu ordenador. El sistema detectará objetos y responderá a tus preguntas sobre ella.',
    guideClassicWebcamBold: 'Webcam',
    guideClassicWebcamText: ': La cámara se queda encendida en tiempo real. Perfecto para hacer preguntas continuas sobre lo que estás enfocando.',
    guideShortcutsTitle: 'Atajos de teclado',
    guideShortcutEnter: 'Enviar tu pregunta rápidamente.',
    guideShortcutShiftEnter: 'Añadir un salto de línea en tu mensaje sin enviarlo.',
    guideShortcutMic: 'Activar o desactivar el micrófono globalmente.',
    detectedObjects: (n: number) => `${n} objeto(s) detectado(s)`,
  },
  en: {
    code: 'en',
    flag: '🇬🇧',
    name: 'English',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
    placeholder: 'What do you want to know about the image?',
    upload: 'Click to upload an image',
    analyze: 'Analyze image',
    analyzing: 'Analyzing...',
    response: 'Response',
    detections: 'Detections',
    history: 'History',
    clear: 'Clear',
    noDetections: 'No detectable objects by YOLO',
    historyEmpty: 'Queries will appear here',
    conversationMode: 'Conversation mode',
    conversationModeDesc: 'Remembers previous questions',
    startAudio: 'Record voice',
    stopAudio: 'Stop recording',
    transcribing: 'Transcribing...',
    tapToStopRecording: 'Tap again to transcribe',
    playAudio: 'Play audio',
    pauseAudio: 'Pause audio',
    send: 'Send',
    activateCameraTooltip: 'You must activate the camera',
    title: 'Mini Assistant',
    subtitle: 'Speak, show, ask — Mini does the rest',
    error: 'Error connecting to backend',
    queryTooLong: 'Your question is too long (maximum 1000 characters).',
    expand: '▼ see more',
    collapse: '▲ close',
    imageMode: 'Image',
    webcamMode: 'Webcam',
    startWebcam: 'Start webcam',
    stopWebcam: 'Stop webcam',
    analyzeError: 'Error analyzing frame',
    webcamError: 'Could not access webcam',
    clearImage: 'Clear image',
    miniGreeting: 'How can I help you today?',
    miniPlaceholder: 'E.g: turn on the camera and tell me what you see...\n(Press Enter to send)',
    tapToSpeak: 'Tap to speak',
    userGuideTitle: 'User Guide',
    guideMiniTitle: 'What is Mini mode?',
    guideMiniIntro1: 'Mini is a multimodal intelligent agent. It not only answers your questions, but ',
    guideMiniIntroBold: 'can perform actions for you',
    guideMiniIntro2: ' depending on what you ask.',
    guideMiniVisualBold: 'Visual autonomy',
    guideMiniVisualText: ': If you ask it to look at something around you, Mini will automatically turn on the webcam or open the file selector.',
    guideMiniVoiceBold: 'Voice and Text',
    guideMiniVoiceText: ': You can type or press the microphone icon to speak directly to it. You can also listen to its answers by clicking the audio icon on each message.',
    guideMiniConvBold: 'Conversation Mode',
    guideMiniConvText: ': Enable it so Mini remembers the context. Ideal for follow-up questions.',
    guideClassicTitle: 'Classic Modes (Image and Webcam)',
    guideClassicIntro: 'Use these if you prefer full manual control over what you send for analysis.',
    guideClassicImageBold: 'Image',
    guideClassicImageText: ': Upload a photo from your computer. The system will detect objects and answer your questions about it.',
    guideClassicWebcamBold: 'Webcam',
    guideClassicWebcamText: ': The camera stays on in real time. Perfect for continuous questions about what you are focusing on.',
    guideShortcutsTitle: 'Keyboard shortcuts',
    guideShortcutEnter: 'Send your question quickly.',
    guideShortcutShiftEnter: 'Add a line break to your message without sending it.',
    guideShortcutMic: 'Toggle the microphone globally.',
    detectedObjects: (n: number) => `${n} detected object(s)`,
  },
  fr: {
    code: 'fr',
    flag: '🇫🇷',
    name: 'Français',
    switchToLight: 'Passer au mode clair',
    switchToDark: 'Passer au mode sombre',
    placeholder: 'Que voulez-vous savoir sur l\'image?',
    upload: 'Cliquez pour télécharger une image',
    analyze: 'Analyser l\'image',
    analyzing: 'Analyse en cours...',
    response: 'Réponse',
    detections: 'Détections',
    history: 'Historique',
    clear: 'Effacer',
    noDetections: 'Aucun objet détectable par YOLO',
    historyEmpty: 'Les requêtes apparaîtront ici',
    conversationMode: 'Mode conversation',
    conversationModeDesc: 'Se souvient des questions précédentes',
    startAudio: 'Enregistrer la voix', 
    stopAudio: 'Arrêter l\'enregistrement',
    transcribing: 'Transcription...',
    tapToStopRecording: 'Appuyez à nouveau pour transcrire',
    playAudio: 'Lire l\'audio',
    pauseAudio: 'Mettre en pause',
    send: 'Envoyer',
    activateCameraTooltip: 'Vous devez activer la caméra',
    title: 'Assistant Mini',
    subtitle: 'Parle, montre, demande — Mini fait le reste',
    error: 'Erreur de connexion au backend',
    queryTooLong: 'Votre question est trop longue (1000 caractères maximum).',
    expand: '▼ voir plus',
    collapse: '▲ fermer',
    imageMode: 'Image',
    webcamMode: 'Webcam',
    startWebcam: 'Activer la webcam',
    stopWebcam: 'Arrêter la webcam',
    analyzeError: 'Erreur lors de l\'analyse du frame',
    webcamError: 'Impossible d\'accéder à la webcam',
    clearImage: 'Supprimer l\'image',
    miniGreeting: 'Comment puis-je vous aider ?',
    miniPlaceholder: 'Ex : allume la caméra et dis-moi ce que tu vois...\n(Appuyez sur Entrée pour envoyer)',
    tapToSpeak: 'Appuyez pour parlerr',
    infoTooltip: 'Info',
    userGuideTitle: 'Guide d\'utilisation',
    guideMiniTitle: 'Qu\'est-ce que le mode Mini ?',
    guideMiniIntro1: 'Mini est un agent intelligent multimodal. Il ne se contente pas de répondre à vos questions, il ',
    guideMiniIntroBold: 'peut effectuer des actions pour vous',
    guideMiniIntro2: ' selon ce que vous lui demandez.',
    guideMiniVisualBold: 'Autonomie visuelle',
    guideMiniVisualText: ': Si vous lui demandez de regarder autour de vous, Mini allumera automatiquement la webcam ou ouvrira le sélecteur de fichiers.',
    guideMiniVoiceBold: 'Voix et Texte',
    guideMiniVoiceText: ': Vous pouvez écrire ou appuyer sur l\'icône du microphone pour lui parler directement. Vous pouvez également écouter ses réponses en cliquant sur l\'icône audio de chaque message.',
    guideMiniConvBold: 'Mode Conversation',
    guideMiniConvText: ': Activez-le pour que Mini se souvienne du contexte. Idéal pour les questions de suivi.',
    guideClassicTitle: 'Modes Classiques (Image et Webcam)',
    guideClassicIntro: 'Utilisez-les si vous préférez avoir un contrôle manuel total sur ce que vous envoyez pour analyse.',
    guideClassicImageBold: 'Image',
    guideClassicImageText: ': Téléchargez une photo de votre ordinateur. Le système détectera les objets et répondra à vos questions.',
    guideClassicWebcamBold: 'Webcam',
    guideClassicWebcamText: ': La caméra reste allumée en temps réel. Parfait pour poser des questions en continu sur ce que vous filmez.',
    guideShortcutsTitle: 'Raccourcis clavier',
    guideShortcutEnter: 'Envoyer votre question rapidement.',
    guideShortcutShiftEnter: 'Ajouter un saut de ligne dans votre message sans l\'envoyer.',
    guideShortcutMic: 'Activer ou désactiver le microphone globalement.',
    detectedObjects: (n: number) => `${n} objet(s) détecté(s)`,
  },
  de: {
    code: 'de',
    flag: '🇩🇪',
    name: 'Deutsch',
    switchToLight: 'In den hellen Modus wechseln',
    switchToDark: 'In den dunklen Modus wechseln',
    placeholder: 'Was möchten Sie über das Bild wissen?',
    upload: 'Klicken Sie, um ein Bild hochzuladen',
    analyze: 'Bild analysieren',
    analyzing: 'Analysiere...',
    response: 'Antwort',
    detections: 'Erkennungen',
    history: 'Verlauf',
    clear: 'Löschen',
    noDetections: 'Keine erkennbaren Objekte durch YOLO',
    historyEmpty: 'Anfragen werden hier angezeigt',
    conversationMode: 'Gesprächsmodus',
    conversationModeDesc: 'Erinnert sich an frühere Fragen',
    startAudio: 'Sprache aufnehmen', 
    stopAudio: 'Aufnahme stoppen',
    transcribing: 'Transkribiere...',
    tapToStopRecording: 'Erneut tippen zum Transkribieren',
    playAudio: 'Audio abspielen',
    pauseAudio: 'Audio pausieren',
    send: 'Senden',
    activateCameraTooltip: 'Sie müssen die Kamera aktivieren',
    title: 'Mini Assistent',
    subtitle: 'Sprich, zeig, frag — Mini macht den Rest',
    error: 'Fehler beim Verbinden mit dem Backend',
    queryTooLong: 'Deine Frage ist zu lang (maximal 1000 Zeichen).',
    expand: '▼ mehr sehen',
    collapse: '▲ schließen',
    imageMode: 'Bild',
    webcamMode: 'Webcam',
    startWebcam: 'Webcam aktivieren',
    stopWebcam: 'Webcam stoppen',
    analyzeError: 'Fehler beim Analysieren des Frames',
    webcamError: 'Zugriff auf Webcam nicht möglich',
    clearImage: 'Bild entfernen',
    miniGreeting: 'Wie kann ich dir helfen?',
    miniPlaceholder: 'Z.B.: schalte die Kamera ein und sag mir was du siehst...\n(Drücken Sie die Eingabetaste zum Senden)',
    tapToSpeak: 'Tippen zum Sprechen',
    infoTooltip: 'Info',
    userGuideTitle: 'Benutzerhandbuch',
    guideMiniTitle: 'Was ist der Mini-Modus?',
    guideMiniIntro1: 'Mini ist ein multimodaler intelligenter Agent. Er beantwortet nicht nur Ihre Fragen, sondern ',
    guideMiniIntroBold: 'kann Aktionen für Sie ausführen',
    guideMiniIntro2: ', je nachdem, was Sie verlangen.',
    guideMiniVisualBold: 'Visuelle Autonomie',
    guideMiniVisualText: ': Wenn Sie ihn bitten, sich etwas in Ihrer Nähe anzusehen, schaltet Mini automatisch die Webcam ein oder öffnet die Dateiauswahl.',
    guideMiniVoiceBold: 'Sprache und Text',
    guideMiniVoiceText: ': Sie können tippen oder auf das Mikrofonsymbol drücken, um direkt mit ihm zu sprechen. Sie können sich die Antworten auch anhören, indem Sie bei jeder Nachricht auf das Audiosymbol klicken.',
    guideMiniConvBold: 'Konversationsmodus',
    guideMiniConvText: ': Aktivieren Sie ihn, damit Mini den Kontext behält. Ideal für Folgefragen.',
    guideClassicTitle: 'Klassische Modi (Bild und Webcam)',
    guideClassicIntro: 'Verwenden Sie diese, wenn Sie die volle manuelle Kontrolle darüber haben möchten, was Sie zur Analyse senden.',
    guideClassicImageBold: 'Bild',
    guideClassicImageText: ': Laden Sie ein Foto hoch. Das System erkennt Objekte und beantwortet Ihre Fragen dazu.',
    guideClassicWebcamBold: 'Webcam',
    guideClassicWebcamText: ': Die Kamera bleibt in Echtzeit eingeschaltet. Perfekt für fortlaufende Fragen zu dem, was Sie gerade fokussieren.',
    guideShortcutsTitle: 'Tastenkombinationen',
    guideShortcutEnter: 'Senden Sie Ihre Frage schnell.',
    guideShortcutShiftEnter: 'Fügen Sie einen Zeilenumbruch hinzu, ohne die Nachricht zu senden.',
    guideShortcutMic: 'Mikrofon global aktivieren oder deaktivieren.',
    detectedObjects: (n: number) => `${n} erkanntes Objekt(e)`,
  },
  it: {
    code: 'it',
    flag: '🇮🇹',
    name: 'Italiano',
    switchToLight: 'Passa alla modalità chiara',
    switchToDark: 'Passa alla modalità scura',
    placeholder: 'Cosa vuoi sapere sull\'immagine?',
    upload: 'Clicca per caricare un\'immagine',
    analyze: 'Analizza immagine',
    analyzing: 'Analisi in corso...',
    response: 'Risposta',
    detections: 'Rilevamenti',
    history: 'Cronologia',
    clear: 'Cancella',
    noDetections: 'Nessun oggetto rilevabile da YOLO',
    historyEmpty: 'Le query appariranno qui',
    conversationMode: 'Modalità conversazione',
    conversationModeDesc: 'Ricorda le domande precedenti',
    startAudio: 'Registra voce', 
    stopAudio: 'Interrompi registrazione',
    transcribing: 'Trascrizione...',
    tapToStopRecording: 'Tocca di nuovo per trascrivere',
    playAudio: 'Riproduci audio',
    pauseAudio: 'Metti in pausa',
    send: 'Invia',
    activateCameraTooltip: 'Devi attivare la fotocamera',
    title: 'Assistente Mini',
    subtitle: 'Parla, mostra, chiedi — Mini fa il resto',
    error: 'Errore di connessione al backend',
    queryTooLong: 'La tua domanda è troppo lunga (massimo 1000 caratteri).',
    expand: '▼ vedi di più',
    collapse: '▲ chiudi',
    imageMode: 'Immagine',
    webcamMode: 'Webcam',
    startWebcam: 'Attiva webcam',
    stopWebcam: 'Disattiva webcam',
    analyzeError: 'Errore durante l\'analisi del frame',
    webcamError: 'Impossibile accedere alla webcam',
    clearImage: 'Rimuovi immagine',
    miniGreeting: 'Come posso aiutarti oggi?',
    miniPlaceholder: 'Es: accendi la fotocamera e dimmi cosa vedi...\n(Premi Invio per inviare)',
    tapToSpeak: 'Tocca per parlare',
    infoTooltip: 'Info',
    userGuideTitle: 'Guida all\'uso',
    guideMiniTitle: 'Cos\'è la modalità Mini?',
    guideMiniIntro1: 'Mini è un agente intelligente multimodale. Non solo risponde alle tue domande, ma ',
    guideMiniIntroBold: 'può eseguire azioni per te',
    guideMiniIntro2: ' a seconda di ciò che gli chiedi.',
    guideMiniVisualBold: 'Autonomia visiva',
    guideMiniVisualText: ': Se gli chiedi di guardare qualcosa intorno a te, Mini accenderà la webcam automaticamente o aprirà il selettore di file.',
    guideMiniVoiceBold: 'Voce e Testo',
    guideMiniVoiceText: ': Puoi scrivergli o premere l\'icona del microfono per parlargli direttamente. Puoi anche ascoltare le sue risposte premendo l\'icona dell\'audio in ogni messaggio.',
    guideMiniConvBold: 'Modalità Conversazione',
    guideMiniConvText: ': Attivala affinché Mini ricordi il contesto. Ideale per fare domande di follow-up.',
    guideClassicTitle: 'Modalità Classiche (Immagine e Webcam)',
    guideClassicIntro: 'Usale se preferisci avere il controllo manuale completo su ciò che stai inviando per l\'analisi.',
    guideClassicImageBold: 'Immagine',
    guideClassicImageText: ': Carica una foto. Il sistema rileverà gli oggetti e risponderà alle tue domande.',
    guideClassicWebcamBold: 'Webcam',
    guideClassicWebcamText: ': La fotocamera rimane accesa in tempo reale. Perfetto per fare domande continue su ciò che stai inquadrando.',
    guideShortcutsTitle: 'Scorciatoie da tastiera',
    guideShortcutEnter: 'Invia rapidamente la tua domanda.',
    guideShortcutShiftEnter: 'Aggiungi un\'interruzione di riga nel messaggio senza inviarlo.',
    guideShortcutMic: 'Attivare o disattivare il microfono a livello globale.',
    detectedObjects: (n: number) => `${n} oggetto/i rilevato/i`,
  },
  pt: {
    code: 'pt',
    flag: '🇵🇹',
    name: 'Português',
    switchToLight: 'Mudar para o modo claro',
    switchToDark: 'Mudar para o modo escuro',
    placeholder: 'O que você quer saber sobre a imagem?',
    upload: 'Clique para enviar uma imagem',
    analyze: 'Analisar imagem',
    analyzing: 'Analisando...',
    response: 'Resposta',
    detections: 'Detecções',
    history: 'Histórico',
    clear: 'Limpar',
    noDetections: 'Nenhum objeto detectável pelo YOLO',
    historyEmpty: 'As consultas aparecerão aqui',
    conversationMode: 'Modo conversa',
    conversationModeDesc: 'Lembra perguntas anteriores',
    startAudio: 'Gravar voz', 
    stopAudio: 'Parar gravação',
    transcribing: 'Transcrevendo...',
    tapToStopRecording: 'Toque novamente para transcrever',
    playAudio: 'Reproduzir áudio',
    pauseAudio: 'Pausar áudio',
    send: 'Enviar',
    activateCameraTooltip: 'Você deve ativar a câmera',
    title: 'Assistente Mini',
    subtitle: 'Fale, mostre, pergunte — Mini faz o resto',
    error: 'Erro ao conectar com o backend',
    queryTooLong: 'Sua pergunta é muito longa (máximo de 1000 caracteres).',
    expand: '▼ ver mais',
    collapse: '▲ fechar',
    imageMode: 'Imagem',
    webcamMode: 'Webcam',
    startWebcam: 'Ativar webcam',
    stopWebcam: 'Parar webcam',
    analyzeError: 'Erro ao analisar o frame',
    webcamError: 'Não foi possível acessar a webcam',
    clearImage: 'Remover imagem',
    miniGreeting: 'Como posso ajudar hoje?',
    miniPlaceholder: 'Ex: ligue a câmera e diga o que vê...\n(Pressione Enter para enviar)',
    tapToSpeak: 'Toque para falar',
    infoTooltip: 'Info',
    userGuideTitle: 'Guia do Usuário',
    guideMiniTitle: 'O que é o modo Mini?',
    guideMiniIntro1: 'Mini é um agente inteligente multimodal. Ele não apenas responde às suas perguntas, mas ',
    guideMiniIntroBold: 'pode realizar ações por você',
    guideMiniIntro2: ' dependendo do que você pedir.',
    guideMiniVisualBold: 'Autonomia visual',
    guideMiniVisualText: ': Se você pedir para ele olhar algo ao seu redor, o Mini ligará automaticamente a webcam ou abrirá o seletor de arquivos.',
    guideMiniVoiceBold: 'Voz e Texto',
    guideMiniVoiceText: ': Você pode digitar ou pressionar o ícone do microfone para falar diretamente com ele. Você também pode ouvir as respostas clicando no ícone de áudio em cada mensagem.',
    guideMiniConvBold: 'Modo Conversação',
    guideMiniConvText: ': Ative-o para que o Mini lembre do contexto. Ideal para perguntas de acompanhamento.',
    guideClassicTitle: 'Modos Clássicos (Imagem e Webcam)',
    guideClassicIntro: 'Use-os se preferir ter controle manual total sobre o que está enviando para análise.',
    guideClassicImageBold: 'Imagem',
    guideClassicImageText: ': Envie uma foto do seu computador. O sistema detectará objetos e responderá às suas perguntas sobre ela.',
    guideClassicWebcamBold: 'Webcam',
    guideClassicWebcamText: ': A câmera fica ligada em tempo real. Perfeito para perguntas contínuas sobre o que você está focando.',
    guideShortcutsTitle: 'Atalhos de teclado',
    guideShortcutEnter: 'Envie sua pergunta rapidamente.',
    guideShortcutShiftEnter: 'Adicione uma quebra de linha na sua mensagem sem enviá-la.',
    guideShortcutMic: 'Ativar ou desativar o microfone globalmente.',
    detectedObjects: (n: number) => `${n} objeto(s) detetado(s)`,
  },
}

export type LanguageCode = keyof typeof languages
export type Translations = typeof languages.es

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  t: Translations
  allLanguages: typeof languages
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('language')
    return (saved as LanguageCode) || 'es'
  })

  const handleSetLanguage = (lang: LanguageCode) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: handleSetLanguage,
      t: languages[language],
      allLanguages: languages,
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage debe usarse dentro de LanguageProvider')
  return ctx
}